name: Go CI

on:
  push:
     branches: [ "main" ,"develop"]
  pull_request:
     branches: [ "main" ,"develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: true 

    - name: Run go vet
      run: make vet

    - name: Build CLI
      run: make build VERSION=ci-test

    - name: Test
      run: make test